language: generic
sudo: required
services:
- docker
cache:
  directories:
    - $GOPATH/pkg/dep
stages:
  - test
  - name: deploy
    if: type != pull_request
jobs:
  include:
    # Test
    - script: echo "test"
    # Deploy
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "deploy"
        on:
          repo: kibbles-n-bytes/service-catalog
          all_branches: true
