make test-integration &> logs/log00.txt
make test-integration &> logs/log01.txt
make test-integration &> logs/log02.txt
make test-integration &> logs/log03.txt
make test-integration &> logs/log04.txt
make test-integration &> logs/log05.txt
make test-integration &> logs/log06.txt
make test-integration &> logs/log07.txt
make test-integration &> logs/log08.txt
make test-integration &> logs/log09.txt
make test-integration &> logs/log10.txt
make test-integration &> logs/log11.txt
make test-integration &> logs/log12.txt
make test-integration &> logs/log13.txt
make test-integration &> logs/log14.txt
make test-integration &> logs/log15.txt
make test-integration &> logs/log16.txt
make test-integration &> logs/log17.txt
make test-integration &> logs/log18.txt
make test-integration &> logs/log19.txt
make test-integration &> logs/log20.txt
make test-integration &> logs/log21.txt
make test-integration &> logs/log22.txt
make test-integration &> logs/log23.txt
make test-integration &> logs/log24.txt
make test-integration &> logs/log25.txt
make test-integration &> logs/log26.txt
make test-integration &> logs/log27.txt
make test-integration &> logs/log28.txt
make test-integration &> logs/log29.txt
make test-integration &> logs/log30.txt
make test-integration &> logs/log31.txt
make test-integration &> logs/log32.txt
make test-integration &> logs/log33.txt
make test-integration &> logs/log34.txt
make test-integration &> logs/log35.txt
make test-integration &> logs/log36.txt
make test-integration &> logs/log37.txt
make test-integration &> logs/log38.txt
make test-integration &> logs/log39.txt
